apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins
  labels:
    app: jenkins
data:
  ldap_organisation: Kibadex
  ldap_domain: kibadex.net
  ldap_tls_ca_crt_filename: kibadex.net.crt
  ldap_tls_crt_filename: ldap.kibadex.net.crt
  ldap_tls_key_filename: ldap.kibadex.net.key
