# Check if working with KMS !
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins
spec:
  backendType: secretsManager
  data:
    - key: /cicd/ldap/kbd-lab-cic-prd-pri
      name: ldap_readonly_password
      property: ldap_readonly_password
